version: "3.9"

services:
  ptart-server:
    command: python manage.py runserver 0.0.0.0:8888
    volumes:
      - ./ptart:/opt/ptart
    ports:
      - "8888:8888"
    environment:
      PYTHONUNBUFFERED: 1
      DJANGO_SETTINGS_MODULE: ptart.settings
